meta:
    image: 'ubuntu'
    pkg: ucsc
    version: 312
env:
    arch: x86_64
prebuild:
    packages: |
        libc6-dev zlib1g-dev libncurses5-dev libmysqlclient-dev unzip
        libpng-dev libssl-dev
build:
    urls:
        - http://hgdownload.soe.ucsc.edu/admin/jksrc.v${version}.zip
    commands:
        - mkdir -p $HOME/bin/${arch}/ /build/dest/bin /build/dest/lib
        - unzip jksrc.v${version}.zip
        - cd kent/src/lib/
        - make
        - cd ../utils/
        - COPT='-O -g -Wl,-rpath,$${ORIGIN}/../lib'
        - ORIGIN='$ORIGIN'
        - export COPT ORIGIN
        - find . -type d -maxdepth 1 -mindepth 1 -exec make -C '{}' \;
        - mv $HOME/bin/${arch}/* /build/dest/bin/
        - |
            for lib in $(ldd /build/dest/bin/faToTwoBit | grep -o '=> /[^ ]*' | sed 's/=> //g'); 
            do
                case $lib in
                    */libcrypto.so*|*/libgcc_s.so*|*/libmysqlclient.so*|*/libssl.so*|*/libstdc++.so*)
                        echo "including $lib";
                        cp $lib /build/dest/lib/;
                        ;;
                esac
            done
        - tar zcf /host/${pkg}-${version}-Linux-${arch}.tar.gz -C /build/dest .
