meta:
    image: 'debian:squeeze'
    version: 1.2
prebuild:
    packages: |
        libc6-dev zlib1g-dev
build:
    urls:
        - https://github.com/samtools/${pkg}/releases/download/${version}/${pkg}-${version}.tar.bz2
    commands:
        - tar jxf ${pkg}-${version}.tar.bz2
        - cd ${pkg}-${version}
        - sed -i.bak 's#/usr/local#/build/dest#' Makefile
        - make
        - make install
        - tar zcf /host/${pkg}-${version}-Linux-x86_64.tar.gz -C /build/dest .
