meta:
    image: 'debian:squeeze'
    version: 1.1.11
prebuild:
    packages: |
        libc6-dev zlib1g-dev
build:
    urls:
        - http://www.cbcb.umd.edu/software/jellyfish/jellyfish-${version}.tar.gz
    commands:
        - tar xfz jellyfish-${version}.tar.gz
        - cd jellyfish-${version}
        - ./configure --prefix=/build/dest
        - make
        - make install
        - tar zcf /host/jellyfish-${version}-Linux-x86_64.tar.gz -C /build/dest .
