meta:
    image: 'debian:squeeze'
    version: 0.1.19
prebuild:
    packages: |
        libc6-dev zlib1g-dev libncurses5-dev
build:
    urls:
        - http://github.com/samtools/samtools/releases/download/${version}/samtools-${version}.tar.bz2
    commands:
        - tar jxf samtools-${version}.tar.bz2
        - cd samtools-${version}
        - make
        - cd htslib-*
        - make bgzip tabix
        - mkdir -p /build/dest/bin /build/dest/lib /build/dest/include/bam
        - cp -f bgzip tabix /build/dest/bin
        - cd ..
        - cp samtools /build/dest/bin
        - cp libbam.a /build/dest/lib
        - cp *.h /build/dest/include/bam
        - tar zcf /host/samtools-${version}-Linux-x86_64.tar.gz -C /build/dest .
