build:
  commands:
  - tar jxf bcftools-${version}.tar.bz2
  - cd bcftools-${version}
  - sed -i.bak 's#/usr/local#/build/dest#' Makefile
  - make
  - make install
  - tar zcf /host/bcftools-${version}-Linux-x86_64.tar.gz -C /build/dest .
  urls:
  - https://github.com/samtools/bcftools/releases/download/${version}/bcftools-${version}.tar.bz2
meta:
  image: debian:squeeze
  version: '1.3'
prebuild:
  packages: 'libc6-dev zlib1g-dev'
